import type { Metadata } from "next";
import Navbar from "./component/Navbar";

export const metadata: Metadata = {
  title: "ebook landing page template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />

        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />

        <link
          href="https://fonts.googleapis.com/css2?family=Unbounded:wght@300;400;600;700&display=swap"
          rel="stylesheet"
        />

        <link href="css/bootstrap.min.css" rel="stylesheet" />

        <link href="css/bootstrap-icons.css" rel="stylesheet" />

        <link href="css/templatemo-ebook-landing.css" rel="stylesheet" />
      </head>

      <body>
        <main>
          <Navbar />

          <section
            className="hero-section d-flex justify-content-center align-items-center"
            id="section_1"
          >
            <div className="container">
              <div className="row">
                <div className="col-lg-6 col-12 mb-5 pb-5 pb-lg-0 mb-lg-0">
                  <h6>Introducing ebook</h6>

                  <h1 className="text-white mb-4">
                    ebook landing page for professionals
                  </h1>

                  <a
                    href="#section_2"
                    className="btn custom-btn smoothscroll me-3"
                  >
                    Discover More
                  </a>

                  <a href="#section_3" className="link link--kale smoothscroll">
                    Meet the Author
                  </a>
                </div>

                <div className="hero-image-wrap col-lg-6 col-12 mt-3 mt-lg-0">
                  <picture>
                    <source
                      media="(max-width: 500px)"
                      srcSet="imgV2/online-books/education-online-books-456.png"
                    />

                    <img
                      src="images/education-online-books.png"
                      className="hero-image img-fluid"
                      alt="education online books"
                      loading="eager"
                      fetchPriority="high"
                    />
                  </picture>
                </div>
              </div>
            </div>
          </section>

          <section className="featured-section">
            <div className="container">
              <div className="row">
                <div className="col-lg-8 col-12">
                  <div className="avatar-group d-flex flex-wrap align-items-center">
                    <picture>
                      <source
                        media="(max-width: 500px)"
                        srcSet="imgV2/avatar1/portrait-beautiful-young-woman-standing-grey-wall-52.jpg"
                      />
                      <img
                        src="images/avatar/portrait-beautiful-young-woman-standing-grey-wall.jpg"
                        className="img-fluid avatar-image"
                        alt=""
                        loading="eager"
                      fetchPriority="high"
                      />
                    </picture>

                    <picture>
                      <source
                        media="(max-width: 500px)"
                        srcSet="imgV2/avatar2/portrait-young-redhead-bearded-male-52.jpg"
                      />
                      <img
                        src="images/avatar/portrait-young-redhead-bearded-male.jpg"
                        className="img-fluid avatar-image avatar-image-left"
                        alt=""
                        loading="eager"
                      fetchPriority="high"
                      />
                    </picture>

                    <picture>
                      <source
                        media="(max-width: 500px)"
                        srcSet="imgV2/avatar3/pretty-blonde-woman-52.jpg"
                      />
                      <img
                        src="images/avatar/pretty-blonde-woman.jpg"
                        className="img-fluid avatar-image avatar-image-left"
                        alt=""
                        loading="eager"
                      fetchPriority="high"
                      />
                    </picture>

                    <picture>
                      <source
                        media="(max-width: 500px)"
                        srcSet="imgV2/avatar4/studio-portrait-emotional-happy-funny-smiling-boyfriend-52.jpg"
                      />
                      <img
                        src="images/avatar/studio-portrait-emotional-happy-funny-smiling-boyfriend.jpg"
                        className="img-fluid avatar-image avatar-image-left"
                        alt=""
                        loading="eager"
                      fetchPriority="high"
                      />
                    </picture>

                    <div className="reviews-group mt-3 mt-lg-0">
                      <strong>4.5</strong>

                      <i className="bi-star-fill"></i>
                      <i className="bi-star-fill"></i>
                      <i className="bi-star-fill"></i>
                      <i className="bi-star-fill"></i>
                      <i className="bi-star"></i>

                      <small className="ms-3">2,564 reviews</small>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <section className="py-lg-5"></section>

          <section className="book-section section-padding" id="section_2">
            <div className="container">
              <div className="row">
                <div className="col-lg-6 col-12">
                  <picture>
                    <source
                      media="(max-width: 500px)"
                      srcSet="imgV2/table-content/tablet-screen-540.jpg"
                    />
                    <img
                      src="images/tablet-screen-contents.jpg"
                      className="img-fluid"
                      alt=""
                      loading="lazy"
                      fetchPriority="low"
                    />
                  </picture>
                </div>

                <div className="col-lg-6 col-12">
                  <div className="book-section-info">
                    <h6>Modern &amp; Creative</h6>

                    <h2 className="mb-4">About The Book</h2>

                    <p>
                      Credit goes to{" "}
                      <a
                        rel="nofollow"
                        href="https://freepik.com"
                        target="_blank"
                      >
                        FreePik
                      </a>{" "}
                      for images used in this ebook landing page template. You
                      may browse FreePik to download more free images for your
                      website.
                    </p>

                    <p>
                      TemplateMo is one of the best websites to download free
                      CSS templates for any purpose. This is an ebook landing
                      page template using Bootstrap 5 CSS layout.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <section>
            <div className="container">
              <div className="row">
                <div className="col-lg-12 col-12 text-center">
                  <h6>What's inside?</h6>

                  <h2 className="mb-5">Preview at glance</h2>
                </div>

                <div className="col-lg-4 col-12">
                  <nav
                    id="navbar-example3"
                    className="h-100 flex-column align-items-stretch"
                  >
                    <nav className="nav nav-pills flex-column">
                      <a className="nav-link smoothscroll" href="#item-1">
                        Introduction
                      </a>

                      <a className="nav-link smoothscroll" href="#item-2">
                        Chapter 1: <strong>Win back your time</strong>
                      </a>

                      <a className="nav-link smoothscroll" href="#item-3">
                        Chapter 2: <strong>Work less, do more</strong>
                      </a>

                      <a className="nav-link smoothscroll" href="#item-4">
                        Chapter 3: <strong>Delegate</strong>
                      </a>

                      <a className="nav-link smoothscroll" href="#item-5">
                        Chapter 4: <strong>Habits</strong>
                      </a>
                    </nav>
                  </nav>
                </div>

                <div className="col-lg-8 col-12">
                  <div
                    data-bs-spy="scroll"
                    data-bs-target="#navbar-example3"
                    data-bs-smooth-scroll="true"
                    className="scrollspy-example-2"
                    tabIndex={0}
                  >
                    <div className="scrollspy-example-item" id="item-1">
                      <h5>Introducing ebook</h5>

                      <p>
                        This ebook landing page is good to use for any purpose.
                        This layout is based on Bootstrap 5 CSS framework.
                      </p>

                      <p>
                        <strong>What is Content Marketing?</strong> If you are
                        wondering what content marketing is all about, this is
                        the place to start.
                      </p>

                      <blockquote className="blockquote">
                        Lorem Ipsum dolor sit amet, consectetur adipsicing
                        kengan omeg kohm tokito
                      </blockquote>

                      <p>
                        When you need free HTML CSS templates, please visit
                        Templatemo website which provides a variety of
                        templates.
                      </p>
                    </div>

                    <div className="scrollspy-example-item" id="item-2">
                      <h5>Win back your time</h5>

                      <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit, sed do eiusmod tempor incididunt ut labore et
                        dolore magna aliqua.
                      </p>

                      <p>
                        Sed leo nisl, posuere at molestie ac, suscipit auctor
                        mauris. Etiam quis metus elementum, tempor risus vel,
                        condimentum orci.
                      </p>

                      <p>
                        You are not allowed to redistribute this template ZIP
                        file on any other template collection website. Please
                        contact TemplateMo for more information.
                      </p>

                      <div className="row">
                        <div className="col-lg-6 col-12 mb-3">
                          <picture>
                            <source
                              media="(max-width: 500px)"
                              srcSet="imgV2/sitting-smiling/smiling-sitting-416.jpg"
                            />
                            <img
                              src="images/portrait-mature-smiling-authoress-sitting-desk.jpg"
                              className="scrollspy-example-item-image img-fluid"
                              alt=""
                              loading="lazy"
                              fetchPriority="low"
                            />
                          </picture>
                        </div>

                        <div className="col-lg-6 col-12 mb-3">
                          <picture>
                            <source
                              media="(max-width: 500px)"
                              srcSet="imgV2/businessman-table/businessman-sitting-416.jpg"
                            />
                            <img
                              src="images/businessman-sitting-by-table-cafe.jpg"
                              className="scrollspy-example-item-image img-fluid"
                              alt=""
                              loading="lazy"
                              fetchPriority="low"
                            />
                          </picture>
                        </div>
                      </div>

                      <p>
                        If you need some specific CSS templates, you can Google
                        with keywords such as templatemo gallery, templatemo
                        digital marketing, etc.
                      </p>
                    </div>

                    <div className="scrollspy-example-item" id="item-3">
                      <h5>Work less, do more</h5>

                      <p>
                        Credit goes to{" "}
                        <a
                          rel="nofollow"
                          href="https://freepik.com"
                          target="_blank"
                        >
                          FreePik
                        </a>{" "}
                        for images used in this ebook landing page template. You
                        may browse FreePik to download more free images for your
                        website.
                      </p>
                      <p>
                        This is a second paragraph. Lorem ipsum dolor sit amet,
                        consectetur adipisicing elit, sed do eiusmod tempor
                        incididunt.
                      </p>

                      <p>
                        Lorem ipsum dolor sit amet, consive adipisicing elit,
                        sed do eiusmod. tempor incididunt ut labore.
                      </p>

                      <div className="row align-items-center">
                        <div className="col-lg-6 col-12">
                          <picture>
                            <source
                              media="(max-width: 500px)"
                              srcSet="imgV2/table-content/tablet-screen-540.jpg"
                            />
                            <img
                              src="images/tablet-screen-contents.jpg"
                              className="img-fluid"
                              alt=""
                              loading="lazy"
                              fetchPriority="low"
                            />
                          </picture>
                        </div>

                        <div className="col-lg-6 col-12">
                          <p>Modern ebook ever</p>

                          <p>
                            <strong>
                              Lorem ipsum dolor sit amet, consive adipisicing
                              elit, sed do eiusmod. tempor incididunt.
                            </strong>
                          </p>
                        </div>
                      </div>
                    </div>

                    <div className="scrollspy-example-item" id="item-4">
                      <h5>Delegate</h5>

                      <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit, sed do eiusmod tempor incididunt ut labore et
                        dolore magna aliqua.
                      </p>

                      <p>
                        Lorem ipsum dolor sit amet, consive adipisicing elit,
                        sed do eiusmod. tempor incididunt ut labore.
                      </p>

                      <p>
                        You are not allowed to redistribute this template ZIP
                        file on any other template collection website. Please
                        contact TemplateMo for more information.
                      </p>

                      <picture>
                        <source
                          media="(max-width: 500px)"
                          srcSet="imgV2/sitting-smiling/smiling-sitting-416.jpg"
                        />
                        <img
                          src="images/portrait-mature-smiling-authoress-sitting-desk.jpg"
                          className="scrollspy-example-item-image img-fluid mb-3"
                          alt=""
                          loading="lazy"
                          fetchPriority="low"
                        />
                      </picture>

                      <p>
                        You may want to contact us for more information about
                        this template.
                      </p>
                    </div>

                    <div className="scrollspy-example-item" id="item-5">
                      <h5>Habits</h5>

                      <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit, sed do eiusmod tempor incididunt ut labore et
                        dolore magna aliqua.
                      </p>

                      <p>
                        You are not allowed to redistribute this template ZIP
                        file on any other template collection website. Please
                        contact TemplateMo for more information.
                      </p>

                      <p>
                        <strong>What is Free CSS Templates?</strong> Free CSS
                        Templates are a variety of ready-made web pages designed
                        for different kinds of websites.
                      </p>

                      <blockquote className="blockquote">
                        Lorem Ipsum dolor sit amet, consectetur adipsicing
                        kengan omeg kohm tokito
                      </blockquote>

                      <p>
                        You may browse TemplateMo website for more CSS
                        templates. Thank you for visiting our website.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <section className="author-section section-padding" id="section_3">
            <div className="container">
              <div className="row">
                <div className="col-lg-6 col-12">
                  <picture>
                    <source
                      media="(max-width: 500px)"
                      srcSet="imgV2/sitting-smiling/smiling-sitting-416.jpg"
                    />
                    <img
                      src="images/portrait-mature-smiling-authoress-sitting-desk.jpg"
                      className="author-image img-fluid"
                      alt=""
                      loading="lazy"
                      fetchPriority="low"
                    />
                  </picture>
                </div>

                <div className="col-lg-6 col-12 mt-5 mt-lg-0">
                  <h6>Meet Author</h6>

                  <h2 className="mb-4">Prof. Sophia</h2>

                  <p>
                    This is an ebook landing page template with Bootstrap 5 CSS
                    framework. It is easy to customize with the use of Bootstrap
                    CSS classes.
                  </p>

                  <p>
                    Lorem ipsum dolor sit amet, consive adipisicing elit, sed do
                    eiusmod. tempor incididunt ut labore.
                  </p>
                </div>
              </div>
            </div>
          </section>

          <section className="reviews-section section-padding" id="section_4">
            <div className="container">
              <div className="row">
                <div className="col-lg-12 col-12 text-center mb-5">
                  <h6>Reviews</h6>

                  <h2>What people saying...</h2>
                </div>

                <div className="col-lg-4 col-12">
                  <div className="custom-block d-flex flex-wrap">
                    <div className="custom-block-image-wrap d-flex flex-column">
                      <picture className="bottom-avatar">
                        <source
                          media="(max-width: 500px)"
                          srcSet="imgV2/avatar1/portrait-beautiful-young-woman-standing-grey-wall-52.jpg"
                        />
                        <img
                          src="images/avatar/portrait-beautiful-young-woman-standing-grey-wall.jpg"
                          className="img-fluid avatar-image"
                          alt=""
                          loading="lazy"
                          fetchPriority="low"
                        />
                      </picture>

                      <div className="text-center mt-3">
                        <span className="text-white">Sandy</span>

                        <strong className="d-block text-white">Artist</strong>
                      </div>
                    </div>

                    <div className="custom-block-info">
                      <div className="reviews-group mb-3">
                        <strong>4.5</strong>

                        <i className="bi-star-fill"></i>
                        <i className="bi-star-fill"></i>
                        <i className="bi-star-fill"></i>
                        <i className="bi-star-fill"></i>
                        <i className="bi-star"></i>
                      </div>

                      <p className="mb-0">
                        Lorem ipsum dolor sit amet, consectetur adipisicing
                        elit, sed do eiusmod tempor incididunt ut labore et
                        dolore magna aliqua.
                      </p>
                    </div>
                  </div>
                </div>

                <div className="col-lg-4 col-12 my-5 my-lg-0">
                  <div className="custom-block d-flex flex-wrap">
                    <div className="custom-block-image-wrap d-flex flex-column">
                      <picture className="bottom-avatar">
                        <source
                          media="(max-width: 500px)"
                          srcSet="imgV2/avatar2/portrait-young-redhead-bearded-male-52.jpg"
                        />
                        <img
                          src="images/avatar/portrait-young-redhead-bearded-male.jpg"
                          className="img-fluid avatar-image avatar-image-left"
                          alt=""
                          loading="lazy"
                          fetchPriority="low"
                        />
                      </picture>

                      <div className="text-center mt-3">
                        <span className="text-white">John</span>

                        <strong className="d-block text-white">Producer</strong>
                      </div>
                    </div>

                    <div className="custom-block-info">
                      <div className="reviews-group mb-3">
                        <strong>3.5</strong>

                        <i className="bi-star-fill"></i>
                        <i className="bi-star-fill"></i>
                        <i className="bi-star-fill"></i>
                        <i className="bi-star"></i>
                        <i className="bi-star"></i>
                      </div>

                      <p className="mb-0">
                        If you need some specific CSS templates, you can Google
                        with keywords such as templatemo one-page, templatemo
                        portfolio, etc.
                      </p>
                    </div>
                  </div>
                </div>

                <div className="col-lg-4 col-12">
                  <div className="custom-block d-flex flex-wrap">
                    <div className="custom-block-image-wrap d-flex flex-column">
                      <picture className="bottom-avatar">
                        <source
                          media="(max-width: 500px)"
                          srcSet="imgV2/avatar3/pretty-blonde-woman-52.jpg"
                        />
                        <img
                          src="images/avatar/pretty-blonde-woman.jpg"
                          className="img-fluid avatar-image"
                          alt=""
                          loading="lazy"
                          fetchPriority="low"
                        />
                      </picture>

                      <div className="text-center mt-3">
                        <span className="text-white">Candy</span>

                        <strong className="d-block text-white">
                          VP, Design
                        </strong>
                      </div>
                    </div>

                    <div className="custom-block-info">
                      <div className="reviews-group mb-3">
                        <strong>5</strong>

                        <i className="bi-star-fill"></i>
                        <i className="bi-star-fill"></i>
                        <i className="bi-star-fill"></i>
                        <i className="bi-star-fill"></i>
                        <i className="bi-star-fill"></i>
                      </div>

                      <p className="mb-0">
                        Please tell your friends about our website that we
                        provide 100% free CSS templates for everyone. Thank you
                        for using our templates.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <section className="contact-section section-padding" id="section_5">
            <div className="container">
              <div className="row">
                <div className="col-lg-5 col-12 mx-auto">
                  <form
                    className="custom-form ebook-download-form bg-white shadow"
                    action="#"
                    method="post"
                    role="form"
                  >
                    <div className="text-center mb-5">
                      <h2 className="mb-1">Get your free ebook</h2>
                    </div>

                    <div className="ebook-download-form-body">
                      <div className="input-group mb-4">
                        <input
                          type="text"
                          name="ebook-form-name"
                          id="ebook-form-name"
                          className="form-control"
                          aria-label="ebook-form-name"
                          aria-describedby="basic-addon1"
                          placeholder="Your Name"
                          required
                        />

                        <span className="input-group-text" id="basic-addon1">
                          <i className="custom-form-icon bi-person"></i>
                        </span>
                      </div>

                      <div className="input-group mb-4">
                        <input
                          type="email"
                          name="ebook-email"
                          id="ebook-email"
                          pattern="[^ @]*@[^ @]*"
                          className="form-control"
                          placeholder="your@company.com"
                          aria-label="ebook-form-email"
                          aria-describedby="basic-addon2"
                          required
                        />

                        <span className="input-group-text" id="basic-addon2">
                          <i className="custom-form-icon bi-envelope"></i>
                        </span>
                      </div>

                      <div className="col-lg-8 col-md-10 col-8 mx-auto">
                        <button type="submit" className="form-control">
                          Download ebook
                        </button>
                      </div>
                    </div>
                  </form>
                </div>

                <div className="col-lg-6 col-12">
                  <h6 className="mt-5">Say hi and talk to us</h6>

                  <h2 className="mb-4">Contact</h2>

                  <p className="mb-3">
                    <i className="bi-geo-alt me-2"></i>
                    London, United Kingdom
                  </p>

                  <p className="mb-2">
                    <a href="tel: 010-020-0340" className="contact-link">
                      010-020-0340
                    </a>
                  </p>

                  <p>
                    <a href="mailto:info@company.com" className="contact-link">
                      info@company.com
                    </a>
                  </p>

                  <h6 className="site-footer-title mt-5 mb-3">Social</h6>

                  <ul className="social-icon mb-4">
                    <li className="social-icon-item">
                      <a href="#" className="social-icon-link bi-instagram"></a>
                    </li>

                    <li className="social-icon-item">
                      <a href="#" className="social-icon-link bi-twitter"></a>
                    </li>

                    <li className="social-icon-item">
                      <a href="#" className="social-icon-link bi-facebook"></a>
                    </li>

                    <li className="social-icon-item">
                      <a href="#" className="social-icon-link bi-whatsapp"></a>
                    </li>
                  </ul>

                  <p className="copyright-text">
                    Copyright © 2048 ebook company
                    <br />
                    <br />
                    <a
                      rel="nofollow"
                      href="https://templatemo.com"
                      target="_blank"
                    >
                      designed by templatemo
                    </a>
                  </p>
                </div>
              </div>
            </div>
          </section>
        </main>
      </body>
    </html>
  );
}
